name: agent-pipeline-test
on:
  push:
env:
  MONGO_URI: mongodb+srv://supercluster.d83jj.mongodb.net/superData
  MONGO_USERNAME: '${{ secrets.MONGO_USERNAME }}'
  MONGO_PASSWORD: '${{ secrets.MONGO_PASSWORD }}'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0

    - name: sh
      shell: bash
      run: npm i

    - name: sh
      env:
        MONGO_URI: mongodb+srv://supercluster.d83jj.mongodb.net/superData
        MONGO_USERNAME: '${{ secrets.MONGO_USERNAME }}'
        MONGO_PASSWORD: '${{ secrets.MONGO_PASSWORD }}'

      shell: bash
      run: npm test
